#!/usr/bin/env python3

import sqlite3

conn = sqlite3.connect('database.db')
c = conn.cursor()

c.execute("""
CREATE TABLE currentPlayer (
    current_player INTEGER
)
""")
c.execute("""CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  password TEST NOT NULL
  )
  """
    
)
c.execute("""CREATE TABLE players (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  gender TEXT NOT NULL CHECK(gender IN ('male','female','other')),
  adventure_name INTEGER,
  room_id INTEGER,
  player_health INTEGER,

  FOREIGN KEY(room_id) REFERENCES rooms(id)
  )
  """
)

c.execute("""CREATE TABLE rooms (
  id INTEGER PRIMARY KEY, 
  name INTEGER NOT NULL,
  message TEXT NOT NULL,
  right_room_id INTEGER,
  left_room_id INTEGER,
          
  FOREIGN KEY(right_room_id) REFERENCES rooms(id)
  FOREIGN KEY(left_room_id) REFERENCES rooms(id)
  )
  """
)

                

conn.commit()